---
services:
  mysql:
    container_name: stage-mysql-imathas
    image: mysql:8.0.33
    domainname: comap.org
    volumes:
      - ./.devcontainer//mysql-data:/var/lib/mysql
      - ./.devcontainer/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - imathas

  certbot:
    container_name: stage-certbot-imathas
    domainname: comap.org
    restart: "no"
    volumes:
      - ./IMathAS:/var/www/html
      - ./.devcontainer/letsencrypt:/etc/letsencrypt
      - ./.devcontainer/letsencrypt/logs:/var/log/letsencrypt
    networks:
      - imathas

  app:
    container_name: stage-app-imathas
    domainname: comap.org
    volumes:
      - ./IMathAS:/var/www/html
      - ./.devcontainer/letsencrypt:/etc/letsencrypt
      - ./.devcontainer/letsencrypt/logs:/var/log/letsencrypt
    ports:
      - "8084:80"
      - "4447:443"
    networks:
      - imathas
