---
services:
  mysql:
    container_name: production-mysql
    image: mysql:lts
    hostname: course-db
    domainname: comap.org
    privileged: false
    stdin_open: false
    tty: false
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/imathas/mysql-data:/var/lib/mysql
      - /opt/docker/imathas/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    command:
      [
        "--general-log=0",
        "--slow-query-log=1",
        "--log-queries-not-using-indexes=1",
        "--long-query-time=10",
        "--max_allowed_packet=256M",
        "--net_read_timeout=600",
        "--net_write_timeout=600",
        "--wait_timeout=28800",
        "--interactive_timeout=28800",
      ]
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
    networks:
      - imathas

  certbot:
    container_name: producion-certbot
    build:
      context: ./docker/certbot
      dockerfile: Dockerfile
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    #   - CERTBOT_DJANGO_HOST=${CERTBOT_DJANGO_HOST}
    #   - CERTBOT_DJANGO_PORT=${CERTBOT_DJANGO_PORT}
    depends_on:
      - app
    volumes:
      - /opt/docker/imathas/letsencrypt:/etc/letsencrypt
      - /opt/docker/imathas/letsencrypt/logs:/var/log/letsencrypt
    restart: "no"
    networks:
      - imathas

  app:
    container_name: production-app
    hostname: course
    domainname: comap.org
    privileged: true
    stdin_open: false
    tty: false
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    expose:
      - 80
      - 443
      - 8080
      - 9000
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    environment:
      - DB_SERVER="${DB_SERVER}"
      - DB_NAME="${DB_NAME}"
      - DB_USERNAME="#{DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - CONFIG_ENV="${CONFIG_ENV}"
    volumes:
      - /opt/docker/imathas/IMathAS:/var/www/html
      - /opt/docker/imathas/letsencrypt:/etc/letsencrypt
      - /opt/docker/imathas/letsencrypt/logs:/var/log/letsencrypt
    networks:
      - imathas

networks:
  imathas:
    driver: bridge
