# https://docs.docker.com/compose/
# https://docs.docker.com/compose/compose-file/

version: '3'

services:

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    expose:
      - 80
      - 443
      - 9000
    ports:
      - "443:443"
      - "80:80"
    links:
      - db
    volumes:
      - "/c/Users/David/Documents/IMathAS:/var/www/html"
      - "./docker/ssl:/etc/ssl/certs"
      - "./docker/ssl:/etc/ssl/private"

    hostname: www
    domainname: imathas.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

    environment:
      DB_SERVER: "db"
      DB_NAME: "imathasdb"
      DB_USERNAME: "imathas"
      DB_PASSWORD: "imathas"
      CONFIG_ENV: "development"

  db:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - "127.0.0.1:3305:3306"
    volumes:
      - "$HOME/docker-data/mysql-imathas:/var/lib/mysql"

    hostname: db
    domainname: imathas.com

    restart: unless-stopped
    privileged: false
    stdin_open: false
    tty: false

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "imathas"
      MYSQL_PASSWORD: "imathas"
      MYSQL_DATABASE: "imathasdb"

