---
services:
    vscode:
        container_name: vscode-imathas
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ../:/workspace:cached
        command: sleep infinity
        networks:
            - imathas-network

networks:
    imathas-network:
        name: imathas-network
